# Generated by Django 5.2.2 on 2025-06-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contato',
        ),
    ]
